/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package cache;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.AbstractAction;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import cache.util.TextTransfer;

/**
 *
 * @author manju
 */
public class AlignmentDisplay extends javax.swing.JInternalFrame {

    static int openFrameCount = 0;
    static final int xOffset = 30, yOffset = 30;
    protected TextTransfer tt = new TextTransfer();

    /**
     * Creates new form AlignmentDisplay
     */
    public AlignmentDisplay() {
        initComponents();
        openFrameCount++;
        setLocation(xOffset * openFrameCount, yOffset * openFrameCount);
    }

    public void setText(String text) {
        scaledTextPane1.setText(text);
        scaledTextPane1.getDocument().putProperty("i18n", Boolean.FALSE);
        scaledTextPane1.getDocument().putProperty("ZOOM_FACTOR", 1.0);
        zoomIn.setAction(new ZoomInAction("Zoom In", KeyEvent.VK_PLUS));
        zoomOut.setAction(new ZoomInAction("Zoom Out", KeyEvent.VK_MINUS));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        saveButton = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        copyButton = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JToolBar.Separator();
        pasteButton = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        zoomIn = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JToolBar.Separator();
        zoomOut = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        scaledTextPane1 = new cache.util.ScaledTextPane();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setMinimumSize(new java.awt.Dimension(250, 250));
        setPreferredSize(new java.awt.Dimension(350, 250));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        jToolBar1.setRollover(true);

        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cache/resources/document-save22.png"))); // NOI18N
        saveButton.setFocusable(false);
        saveButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        saveButton.setMaximumSize(new java.awt.Dimension(25, 25));
        saveButton.setMinimumSize(new java.awt.Dimension(25, 25));
        saveButton.setPreferredSize(new java.awt.Dimension(25, 25));
        saveButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(saveButton);
        jToolBar1.add(jSeparator1);

        copyButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cache/resources/edit-copy22.png"))); // NOI18N
        copyButton.setFocusable(false);
        copyButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        copyButton.setMaximumSize(new java.awt.Dimension(25, 25));
        copyButton.setMinimumSize(new java.awt.Dimension(25, 25));
        copyButton.setPreferredSize(new java.awt.Dimension(25, 25));
        copyButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        copyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(copyButton);
        jToolBar1.add(jSeparator2);

        pasteButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cache/resources/edit-paste22.png"))); // NOI18N
        pasteButton.setFocusable(false);
        pasteButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pasteButton.setMaximumSize(new java.awt.Dimension(25, 25));
        pasteButton.setMinimumSize(new java.awt.Dimension(25, 25));
        pasteButton.setPreferredSize(new java.awt.Dimension(25, 25));
        pasteButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pasteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasteButtonActionPerformed(evt);
            }
        });
        jToolBar1.add(pasteButton);
        jToolBar1.add(jSeparator3);

        zoomIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cache/resources/View-zoom-in.png"))); // NOI18N
        zoomIn.setFocusable(false);
        zoomIn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        zoomIn.setMaximumSize(new java.awt.Dimension(25, 25));
        zoomIn.setMinimumSize(new java.awt.Dimension(25, 25));
        zoomIn.setPreferredSize(new java.awt.Dimension(25, 25));
        zoomIn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        zoomIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoomInActionPerformed(evt);
            }
        });
        jToolBar1.add(zoomIn);
        jToolBar1.add(jSeparator4);

        zoomOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cache/resources/View-zoom-out.png"))); // NOI18N
        zoomOut.setFocusable(false);
        zoomOut.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        zoomOut.setMaximumSize(new java.awt.Dimension(25, 25));
        zoomOut.setMinimumSize(new java.awt.Dimension(25, 25));
        zoomOut.setPreferredSize(new java.awt.Dimension(25, 25));
        zoomOut.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        zoomOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zoomOutActionPerformed(evt);
            }
        });
        jToolBar1.add(zoomOut);

        jScrollPane1.setViewportView(scaledTextPane1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jToolBar1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jToolBar1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 34, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        FileFilter fileFilter = new FileNameExtensionFilter("Alignment File Filter", "txt");
        JFileChooser fc = new JFileChooser();
        fc.setName("Save Alignment");
        fc.setFileFilter(fileFilter);
        int option = fc.showSaveDialog(this);
        if (JFileChooser.APPROVE_OPTION == option) {
            try {
                File file = fc.getSelectedFile();
                BufferedWriter bw = new BufferedWriter(new FileWriter(file));
                bw.write(scaledTextPane1.getText());
                bw.flush();
                bw.close();
            } catch (IOException ioe) {
                ioe.printStackTrace();
            }
        }
    }//GEN-LAST:event_saveButtonActionPerformed

    private void copyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyButtonActionPerformed
        tt.setClipboardContents(scaledTextPane1.getSelectedText());
    }//GEN-LAST:event_copyButtonActionPerformed

    private void pasteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasteButtonActionPerformed
        scaledTextPane1.replaceSelection(tt.getClipboardContents());
    }//GEN-LAST:event_pasteButtonActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        openFrameCount--;
    }//GEN-LAST:event_formInternalFrameClosed

    private void zoomOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoomOutActionPerformed
        scaledTextPane1.getZoomOutListener().actionPerformed(evt);
    }//GEN-LAST:event_zoomOutActionPerformed

    private void zoomInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zoomInActionPerformed
        scaledTextPane1.getZoomInListener().actionPerformed(evt);
    }//GEN-LAST:event_zoomInActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton copyButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JToolBar.Separator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar.Separator jSeparator4;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton pasteButton;
    private javax.swing.JButton saveButton;
    private cache.util.ScaledTextPane scaledTextPane1;
    private javax.swing.JButton zoomIn;
    private javax.swing.JButton zoomOut;
    // End of variables declaration//GEN-END:variables

    class ZoomInAction extends AbstractAction {

        public ZoomInAction(String desc, Integer mnemonic) {
            super();
            putValue(SHORT_DESCRIPTION, desc);
            putValue(MNEMONIC_KEY, mnemonic);
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            zoomInActionPerformed(e);
        }
    }

    class ZoomOutAction extends AbstractAction {

        public ZoomOutAction(String desc, Integer mnemonic) {
            super();
            putValue(SHORT_DESCRIPTION, desc);
            putValue(MNEMONIC_KEY, mnemonic);
        }

        @Override
        public void actionPerformed(ActionEvent e) {
            zoomOutActionPerformed(e);
        }
    }
}
